# Generated by Django 5.2.8 on 2025-11-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedsong',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
