# Generated by Django 5.2.8 on 2025-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_generatedsong_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedsong',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_covers/'),
        ),
    ]
