# Generated by Django 5.2.8 on 2025-11-28 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_generatedsong_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedsong',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_generated_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
